#11 task Aba sobre feita
MSB-ServicosTI/ERPMSB pull request #44
Opened 2023-09-19 06:10 UTC by matheusplesky

task feita com amor e carinho

2023-09-19 11:33 UTC, OG4rcia approved these changes
boa man

2023-09-19 14:53 UTC, guil-hanma commented on ERPWINFORMS/View/Home.cs
> +            informaçõesToolStripMenuItem = new ToolStripMenuItem();
Isso é mais uma duvida minha, mas não pode vir a dar problemas usarmos acentuações no código, como o de "informações".

2023-09-19 14:58 UTC, guil-hanma commented on ERPWINFORMS/View/TelaInicial.cs
> +
Para qual finalidade esses dois eventos foram criados? Não encontrei eles em nenhum outro lugar do codigo

2023-09-19 16:59 UTC, OG4rcia commented on ERPWINFORMS/View/Home.cs
> +            informaçõesToolStripMenuItem = new ToolStripMenuItem();
eita, não tinha visto, sim, com certeza vai dar problemas, tem que ficar informcoes.

2023-09-19 17:00 UTC, OG4rcia commented on ERPWINFORMS/View/Home.cs
> +            informaçõesToolStripMenuItem = new ToolStripMenuItem();
informacoes

2023-09-19 17:03 UTC, OG4rcia requested changes
tem duas observações do Gui código, precisam ser corrigidas pra não vir a dar problemas futuramente.

2023-09-19 20:04 UTC, matheusplesky commented on ERPWINFORMS/View/Home.cs
> +            informaçõesToolStripMenuItem = new ToolStripMenuItem();
informações alteradas

2023-09-19 20:05 UTC, MusinxFate approved these changes

2023-09-20 02:07 UTC, OG4rcia approved these changes

2023-09-20 02:07 UTC, merged